### ISSUE TITLE
Rename 'dummy' to a more suitable name to prevent potential conflicts

### ISSUE THREAD

**Issue by hacker-h** [inovex/illuminatio#57] opened 2019-08-23 12:12 UTC
Currently all pods created by illuminatio are named 'dummy'; this should be changes by generating a random name to prevent conflicts.

**Comment by beH3uH** [comment] 2019-08-23 19:21
Hi,

I'm new to github, and don't really know how to upload the updates. It didn't let me.

Here are the edits:
src/illuminatio/test_orchestrator.py:
...
**import random
import string**
...
...
...
    **def create_random_dummy_name(stringLength=20):
       letters =  string.ascii_lowercase
       return ''.join(random.choice(letters) for i in range(stringLength))**


    def _find_or_create_cluster_resources_for_cases(self, cases_dict, api: k8s.client.CoreV1Api):
        resolved_cases = {}
        from_host_mappings = {}
        to_host_mappings = {}
        port_mappings = {}
        for from_host_string, target_dict in cases_dict.items():
            from_host = Host.from_identifier(from_host_string)
            logger.debug("Searching pod for host " + str(from_host))
            if not (isinstance(from_host, ClusterHost) or isinstance(from_host, GenericClusterHost)):
                raise ValueError("Only ClusterHost and GenericClusterHost fromHosts are supported by this Orchestrator")
            namespaces_for_host = self._find_or_create_namespace_for_host(from_host, api)
            from_host = ClusterHost(namespaces_for_host[0].metadata.name, from_host.pod_labels)
            logger.debug("Updated fromHost with found namespace: " + str(from_host))
            pods_for_host = [pod for pod in self._current_pods if from_host.matches(pod)]
            # create pod if none for fromHost is in cluster (and add it to podsForHost)
            if not pods_for_host:
                **dummy_name = "dummy_" + create_random_dummy_name()**
                logger.debug("Creating dummy pod for host " + str(from_host))
                additional_labels = {ROLE_LABEL: "from_host_dummy", CLEANUP_LABEL: CLEANUP_ALWAYS}
                container = k8s.client.V1Container(image="nginx:stable", name=**dummy_name**)
                dummy = init_pod(from_host, additional_labels, PROJECT_PREFIX + **"-" + dummy_name + "-",** container)

**Comment by hacker-h** [comment] 2019-08-26 00:27
Hi, thank you for contribution.
Please fork the repository and create a new branch for your pull request.
For more details see https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by maxbischoff** [comment] 2019-09-10 09:33
Looking at the code, we already let kubernetes generate a random name using the scheme `illuminatio-dummy-<random>`. What would a more suitable name look like in your opinion?

**Comment by maxbischoff** [comment] 2019-09-11 07:57
Closing this, as kubernetes should ensure that a unique random suffix is generated. Feel free to reopen, if you find it doesn't work as intended

**Closed by maxbischoff** 2019-09-11 07:57 UTC
Labels: cleanup, good first issue
